sudo: false
language: java
addons:
  sonarqube:
    organization: "jcgay-github"
    token:
      secure: "MLW7muRsJiF3Cwrqa/UFeKwNJzSd8g0WVZ30d6Yyy2egkbTiZ2M9U7/WfXQwV1Fd4lMjEOXFyrRcH3cBla4dMRG9JQLGEsBr1FGRJZZ3JiA01hTEWu9bD9vZM0pIj0X8psLZ+NoepzPWrhgMR+AUwrOSaKK95qx2ncEgWq3lAO4="
before_install:
  - jdk_switcher use oraclejdk8
install:
  - mvn install -DskipTests=true -B -V
script:
  - mvn package sonar:sonar -Prun-coverage -B
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings etc/deploy-settings.xml"
  - mvn verify coveralls:report -Prun-coverage
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
env:
  global:
    - secure: cttGV5bt0VuZZXHK0yo9rfszAjX67+pcRKMBjGuFEdr3v8uD55ho2qrXAtKEbG5x/g1atBXKD3HhBzK5Mb00XDkF93TQdX9veO6619xcVqQ7LdzPDIbbpX7lrS7vIaUaM77+hCtHFEKZs6+DVyeL93z0Vy7GiIAnRAnGomlmAwc=
    - secure: bjSYB4bs3FXRt9kPkPE3Qex00rckmnrKc1SoNiDXJ9ZHVjGRl3SXjcAUDQiTvmfliuUBMSRryCpjR4xqUywICEwD8tg9ubW7EbI8X12yxtGszJCoGQYTSlVc/bVgM+qaT/KxLvoCI3PTsPgEI/DsSIjmM4uVqzStgcgb02qZWE8=
